export const ADD_REMINDER_REQUEST = "ADD_REMINDER_REQUEST";
export const ADD_REMINDER_SUCCESS = "ADD_REMINDER_SUCCESS";
export const ADD_REMINDER_FAIL = "ADD_REMINDER_FAIL";

export const EDIT_REMINDER_REQUEST = "EDIT_REMINDER_REQUEST";
export const EDIT_REMINDER_SUCCESS = "EDIT_REMINDER_SUCCESS";
export const EDIT_REMINDER_FAIL = "EDIT_REMINDER_FAIL";

export const PUSH_REMINDER_REQUEST = "PUSH_REMINDER_REQUEST";
export const PUSH_REMINDER_SUCESS = "PUSH_REMINDER_SUCESS";
export const PUSH_REMINDER_FAIL = "PUSH_REMINDER_FAIL";
